//
//  CalculationSnapshot.swift
//  PropertyDealRealityChecker
//
//  Stage 3 — Deterministic Calculation Engine
//  Architectural Mandate: Immutable audit record produced by every completed calculation (ADR-003 / Rule 5).
//  Embeds unrounded metrics, verdicts, reason codes, and multi-dimensional sensitivity matrices.
//

import Foundation
import CalculationKit

/// Encapsulates the multi-dimensional sensitivity and stress-test matrix results generated by Stage 3 (`CalculationKit`).
public struct StressTestResults: Sendable, Codable, Hashable {
    /// Summary description of the stress evaluation.
    public let summary: String
    /// The structured 3x3 or 5x5 sensitivity matrix evaluated by `SensitivityEngine`.
    public let matrix: SensitivityMatrix?
    
    /// Initializes stress-test results.
    public init(
        summary: String = "Base stress matrix",
        matrix: SensitivityMatrix? = nil
    ) {
        self.summary = summary
        self.matrix = matrix
    }
}

/// An immutable, append-only audit record produced whenever an underwriting calculation completes.
///
/// Mandated by Blueprint Section 4.5 ("Snapshot and Audit Architecture") and ADR-003:
/// "Every completed calculation must produce an immutable `CalculationSnapshot` containing
/// input hash, formula version, metrics, flags, and verdict."
///
/// Once created, a `CalculationSnapshot` is never mutated. Editing a deal creates a new snapshot.
public struct CalculationSnapshot: Sendable, Codable, Hashable, Identifiable {
    /// Unique identifier for this audit snapshot.
    public let id: UUID
    
    /// Aggregate root deal ID that produced this snapshot.
    public let dealID: UUID
    
    /// Underwriting scenario ID evaluated in this snapshot.
    public let scenarioID: UUID
    
    /// Formula engine version from `CalculationKit` (e.g., `"1.0.0"`).
    public let engineVersion: String
    
    /// Rule-set version from `DealCore` (e.g., `"Rental-US-1.0"`).
    public let ruleSetVersion: String
    
    /// Timestamp when this calculation snapshot was generated.
    public let createdAt: Date
    
    /// Deterministic SHA-256 equivalent hash of `normalizedInputs`.
    public let inputHash: String
    
    /// The immutable normalized inputs used to generate this snapshot.
    public let normalizedInputs: CanonicalDeal
    
    /// Any non-blocking informational warnings detected during validation.
    public let validationFindings: [ValidationIssue]
    
    /// The calculated unrounded financial metrics.
    public let metrics: CalculationMetrics
    
    /// The assigned profitability category, confidence level, and structured reason codes.
    public let verdict: Verdict
    
    /// Sensitivity matrix and stress-test results.
    public let stressResults: StressTestResults?
    
    /// Initializes an immutable calculation snapshot.
    public init(
        id: UUID = UUID(),
        dealID: UUID,
        scenarioID: UUID,
        engineVersion: String = CalculationKitModule.engineVersion,
        ruleSetVersion: String = DealCoreModule.ruleSetVersion,
        createdAt: Date = Date(),
        inputHash: String,
        normalizedInputs: CanonicalDeal,
        validationFindings: [ValidationIssue] = [],
        metrics: CalculationMetrics,
        verdict: Verdict,
        stressResults: StressTestResults? = nil
    ) {
        self.id = id
        self.dealID = dealID
        self.scenarioID = scenarioID
        self.engineVersion = engineVersion
        self.ruleSetVersion = ruleSetVersion
        self.createdAt = createdAt
        self.inputHash = inputHash
        self.normalizedInputs = normalizedInputs
        self.validationFindings = validationFindings
        self.metrics = metrics
        self.verdict = verdict
        self.stressResults = stressResults
    }
}
