//
//  PDFReportGenerator.swift
//  PropertyDealRealityChecker
//
//  Stage 7 — Explanation & Reports
//  Architectural Mandate: Branded PDF summary reports.
//

import Foundation
import CoreGraphics
#if canImport(PDFKit)
import PDFKit
#endif
#if canImport(UIKit)
import UIKit
#endif
import DealCore

/// Uses CoreGraphics/PDFKit to render a shareable PDF summary of a calculation snapshot.
public struct PDFReportGenerator: Sendable {
    
    public init() {}
    
    /// Generates PDF data from a calculation snapshot and its verdict summary.
    /// - Parameters:
    ///   - snapshot: The immutable snapshot of the deal calculation.
    ///   - summaryText: The plain-language executive summary generated by ExplanationKit.
    /// - Returns: A `Data` object containing the PDF.
    public func generateReport(snapshot: CalculationSnapshot, summaryText: String) -> Data {
        let pdfMetaData = [
            kCGPDFContextCreator: "Property Deal Reality Checker",
            kCGPDFContextAuthor: "Investor",
            kCGPDFContextTitle: "Deal Evaluation Report"
        ]
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        let pageWidth = 8.5 * 72.0
        let pageHeight = 11.0 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        
        let data = renderer.pdfData { (context) in
            context.beginPage()
            
            // Draw Title
            let titleAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 24)
            ]
            let titleStr = "Deal Evaluation Report"
            let titleRect = CGRect(x: 50, y: 50, width: pageWidth - 100, height: 40)
            titleStr.draw(in: titleRect, withAttributes: titleAttributes)
            
            // Draw Executive Summary
            let summaryAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 12)
            ]
            let summaryRect = CGRect(x: 50, y: 100, width: pageWidth - 100, height: 100)
            summaryText.draw(in: summaryRect, withAttributes: summaryAttributes)
            
            // Draw Metrics Header
            let metricsHeaderStr = "Key Financial Metrics"
            let metricsHeaderAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 16)
            ]
            let metricsHeaderRect = CGRect(x: 50, y: 220, width: pageWidth - 100, height: 30)
            metricsHeaderStr.draw(in: metricsHeaderRect, withAttributes: metricsHeaderAttributes)
            
            // Draw Metrics
            let m = snapshot.metrics
            let metricsString = """
            Net Operating Income: \(m.netOperatingIncome.amount)
            Owner Cash Flow: \(m.ownerCashFlow.amount)
            Cap Rate: \(m.capRate.fraction)
            Cash on Cash Return: \(m.cashOnCashReturn.fraction)
            DSCR: \(m.dscr)
            """
            
            let metricsAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.monospacedSystemFont(ofSize: 12, weight: .regular)
            ]
            let metricsRect = CGRect(x: 50, y: 260, width: pageWidth - 100, height: 200)
            metricsString.draw(in: metricsRect, withAttributes: metricsAttributes)
        }
        
        return data
    }
}
